// Frontend Configuration
// This file is used for local development
// In production, this file is auto-generated by Terraform deployment

export const config = {
  apiBaseUrl: 'http://localhost:8080/api/v1'
};
