// Auto-generated by Terraform - DO NOT EDIT
// Environment: ${environment}
// Generated: ${timestamp}

export const config = {
  apiBaseUrl: 'https://flyhalf-prod-api-oas33witna-uc.a.run.app/api/v1'
};
